# Generated by Django 4.0.2 on 2022-03-02 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextgenqa_contributor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nextgenqa_contributor',
            old_name='user_email',
            new_name='contrib_user_email',
        ),
        migrations.RenameField(
            model_name='nextgenqa_contributor',
            old_name='user_first_name',
            new_name='contrib_user_first_name',
        ),
        migrations.RenameField(
            model_name='nextgenqa_contributor',
            old_name='user_id',
            new_name='contrib_user_id',
        ),
        migrations.RenameField(
            model_name='nextgenqa_contributor',
            old_name='user_last_name',
            new_name='contrib_user_last_name',
        ),
        migrations.RenameField(
            model_name='nextgenqa_contributor',
            old_name='user_password',
            new_name='contrib_user_password',
        ),
        migrations.RenameField(
            model_name='nextgenqa_contributor',
            old_name='user_phone',
            new_name='contrib_user_phone',
        ),
        migrations.RenameField(
            model_name='nextgenqa_contributor',
            old_name='username',
            new_name='contrib_username',
        ),
        migrations.RemoveField(
            model_name='nextgenqa_contributor',
            name='user_password2',
        ),
    ]
